import pygame
background2 = pygame.image.load('files/images/levels/background1.png')
background3 = pygame.image.load('files/images/levels/background2.png')
background4 = pygame.image.load('files/images/levels/background3.png')
background5 = pygame.image.load('files/images/levels/background4.png')
background5a = pygame.image.load('files/images/levels/background4_a.png')
gameover_screen = pygame.image.load('files/images/levels/gameover.png')
player1 = pygame.image.load('files/images/player/player1.png')
player1_a = pygame.image.load('files/images/player/player1_a.png')
end1_screen = pygame.image.load('files/images/levels/end1.png')
end2_screen = pygame.image.load('files/images/levels/end2.png')